// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace tilemgr.Migrations
{
    [DbContext(typeof(ProjectContext))]
    [Migration("20260505132313_CanvasCleanup")]
    partial class CanvasCleanup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("Tilemgr.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Tilemgr.Project", b =>
                {
                    b.OwnsOne("Tilemgr.Canvas", "canvas", b1 =>
                        {
                            b1.Property<int>("ProjectId")
                                .HasColumnType("INTEGER");

                            b1.Property<byte[]>("Compressed")
                                .IsRequired()
                                .HasColumnType("BLOB");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.OwnsOne("Tilemgr.Palette", "palette", b1 =>
                        {
                            b1.Property<int>("ProjectId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ImgPath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("TileHei")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("TileWid")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ProjectId");

                            b1.ToTable("Projects");

                            b1.WithOwner()
                                .HasForeignKey("ProjectId");
                        });

                    b.Navigation("canvas")
                        .IsRequired();

                    b.Navigation("palette")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
